file_format: "1"
id: think_corne
name: ThinkCorne
type: shield
url: https://github.com/infused-kim/kb_think_corney
requires: [pro_micro]
features:
  - keys
  - display
siblings:
  - think_corne_left
  - think_corne_right
